# Generated by Django 5.1.6 on 2025-02-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_livros', '0002_emprestimo_devolvido'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='editora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.CharField(blank=True, choices=[('Ficção', 'Ficção'), ('Não Ficção', 'Não Ficção'), ('Romance', 'Romance'), ('Suspense', 'Suspense'), ('Aventura', 'Aventura'), ('Ciência', 'Ciência'), ('História', 'História')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='isbn',
            field=models.CharField(default=1, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='num_paginas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
