# Generated by Django 5.1.6 on 2025-03-23 05:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_livros', '0003_livro_data_aquisicao_livro_descricao_livro_editora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='observacao',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='tombamento',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
