# Generated by Django 5.1.6 on 2025-03-23 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_livros', '0008_livro_tombamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='devolvido',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_prevista_devolucao',
            field=models.DateField(default=datetime.datetime(2025, 3, 30, 20, 10, 19, 649100, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='nome_emprestado_para',
            field=models.CharField(default='joao', max_length=200),
            preserve_default=False,
        ),
    ]
