# Generated by Django 5.1.6 on 2025-03-24 00:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_livros', '0010_leitor_alter_emprestimo_data_prevista_devolucao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='nome_emprestado_para',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='leitor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_livros.leitor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista_devolucao',
            field=models.DateField(default=datetime.datetime(2025, 3, 31, 0, 53, 9, 418612, tzinfo=datetime.timezone.utc)),
        ),
    ]
