# Generated by Django 5.1.6 on 2025-03-24 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_livros', '0011_remove_emprestimo_nome_emprestado_para_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista_devolucao',
            field=models.DateField(default=datetime.datetime(2025, 3, 31, 0, 54, 34, 595397, tzinfo=datetime.timezone.utc)),
        ),
    ]
