# Generated by Django 5.1.6 on 2025-03-24 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_livros', '0012_alter_emprestimo_data_prevista_devolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista_devolucao',
            field=models.DateField(default=datetime.datetime(2025, 3, 31, 1, 0, 11, 951683, tzinfo=datetime.timezone.utc)),
        ),
    ]
