# Generated by Django 5.1.6 on 2025-03-24 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_livros', '0013_alter_emprestimo_data_prevista_devolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='estado_conservacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='observacoes_conservacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista_devolucao',
            field=models.DateField(default=datetime.datetime(2025, 3, 31, 5, 21, 48, 402843, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
