# Generated by Django 5.1.6 on 2025-03-24 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_livros', '0014_emprestimo_estado_conservacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista_devolucao',
            field=models.DateField(default=datetime.datetime(2025, 3, 31, 5, 24, 24, 80825, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='estado_conservacao',
            field=models.CharField(blank=True, choices=[('ótimo', 'Ótimo'), ('bom', 'Bom'), ('regular', 'Regular'), ('ruim', 'Ruim'), ('danificado', 'Danificado')], max_length=50, null=True),
        ),
    ]
