# Generated by Django 5.1.6 on 2025-05-06 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_livros', '0018_alter_emprestimo_data_prevista_devolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista_devolucao',
            field=models.DateField(default=datetime.datetime(2025, 5, 13, 2, 1, 29, 99219, tzinfo=datetime.timezone.utc)),
        ),
    ]
